# docker-compose.yml — Day 5
services:
  policysimplify:
    build: .
    ports:
      - "8080:8080"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      APP_PASSCODE: ${APP_PASSCODE}
      COUNCIL_NAME: ${COUNCIL_NAME:-Your Council}
      RETENTION_DAYS: "30"
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      LOG_LEVEL: INFO
    volumes:
      - ./data:/app
